In [6]:
import numpy as np


Gaussian line profile

parameters 

wav = wavelength , shape = (N,), linespace, angstrom

wav0 = central wavelength , shape(N,),array,angstrom

sigma = line width ,float, angstrom

amp = amplitude or depth , float , dimension less

 


In [23]:
wav = np.linspace(4990,5010,1000)
wav0 = np.asarray(5000.0)
print(wav0.ndim)
wave0 = np.array([5000,5000.50,5010])
sigma = 1.0
amp = 1.0
def Gaussian_line(wav,wav0,sigma,amp):
    result = amp*(np.exp(-(wav - wav0)**2) / (2 * sigma**2))
    return result

0


In [8]:
profile = Gaussian_line(wav,wav0,sigma,amp)
profile.shape

(1000,)

This follows the the normal rule

the wav shape is (1000,),
the wav0 shape is (1,)

so it becomes (1000,)

In [9]:
def Gaussian_line(wav,wav0,sigma,amp):
    result = amp*(np.exp(-(wav[:,np.newaxis] - wav0[np.newaxis,:])**2) / (2 * sigma**2))
    return result
profile = Gaussian_line(wav,wave0,sigma,amp)
profile.shape

(1000, 3)

this is an exception 

here according to normal rule 
(1000,)
(3,)

gives error 

so x[:,np.newaxis] is use on second one and its reverse on first one so they became


(1000,1)

(1,3)


(1000,3)

In [30]:
if wav0.ndim == 0:
    result =  amp*(np.exp(-(wav - wav0)**2) / (2 * sigma**2))
    x =1
else:
    result = amp*(np.exp(-(wav[:,np.newaxis] - wav0[np.newaxis,:])**2) / (2 * sigma**2))
    x =2

print(result,x)

[1.86003799e-44 2.77484950e-44 4.13627038e-44 6.16070304e-44
 9.16861000e-44 1.36341665e-43 2.02584192e-43 3.00769908e-43
 4.46185119e-43 6.61374808e-43 9.79562348e-43 1.44966745e-42
 2.14366323e-42 3.16735396e-42 4.67615081e-42 6.89814449e-42
 1.01678220e-41 1.49752971e-41 2.20381346e-41 3.24060489e-41
 4.76134009e-41 6.99011292e-41 1.02539465e-40 1.50296814e-40
 2.20120438e-40 3.22123813e-40 4.71017630e-40 6.88182084e-40
 1.00466536e-39 1.46551871e-39 2.13605865e-39 3.11090569e-39
 4.52701974e-39 6.58248380e-39 9.56354879e-39 1.38835403e-38
 2.01387839e-38 2.91889267e-38 4.22722028e-38 6.11707072e-38
 8.84471802e-38 1.27783962e-37 1.84467804e-37 2.66082721e-37
 3.83499354e-37 5.52286554e-37 7.94723712e-37 1.14266715e-36
 1.64162962e-36 2.35658162e-36 3.38019427e-36 4.84454177e-36
 6.93770161e-36 9.92728288e-36 1.41937466e-35 2.02775539e-35
 2.89458262e-35 4.12865130e-35 5.88413094e-35 8.37931120e-35
 1.19230175e-34 1.69518035e-34 2.40822747e-34 3.41846369e-34
 4.84859943e-34 6.871530

In [31]:
if wave0.ndim == 0:
    result =  amp*(np.exp(-(wav - wav0)**2) / (2 * sigma**2))
    x =1
else:
    result = amp*(np.exp(-(wav[:,np.newaxis] - wave0[np.newaxis,:])**2) / (2 * sigma**2))
    x =2

print(result,x)

[[1.86003799e-044 6.57662947e-049 9.57584798e-175]
 [2.77484950e-044 1.00095736e-048 2.13199679e-174]
 [4.13627038e-044 1.52222780e-048 4.74294095e-174]
 ...
 [4.13627038e-044 6.81696321e-040 4.99199040e-001]
 [2.77484950e-044 4.66569180e-040 4.99799640e-001]
 [1.86003799e-044 3.19075172e-040 5.00000000e-001]] 2
